- name: Create Docker images directory
  file:
    path: "{{compose_dir}}/images"
    state: directory
    mode: "0755"

- name: Create contexts for php/apache backends
  file:
    path: "{{compose_dir}}/images/php-{{ item.backend_php_version | default (default_php_version) }}-bitrix"
    state: directory
    mode: "0755"
  loop: "{{ bitrixsites | flatten(levels=1) }}"

- name: Generate Dockerfiles for php/apache backends
  template:
    src: "bitrix/dockerfile-bitrix.j2"
    dest: "{{compose_dir}}/images/php-{{ item.backend_php_version | default (default_php_version) }}-bitrix/Dockerfile"
    force: yes
    backup: yes
  loop: "{{ bitrixsites | flatten(levels=1) }}"
  notify: compose_build_images
