---
# Bitrix-based Web sites configuration

- name: "{{ site.sitename }} - Create Bitrix-based Web sites directory tree"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}-bitrix/{{ item }}"
    state: directory
    mode: "0755"
    owner: www-data
    group: www-data
  loop:
    - "wwwroot"
    - "db"
    - "config"
    - "config/nginx"
    - "log"

- name: "{{ site.sitename }} - Check if instance needs to be initialized"
  find:
    paths: "{{ sites_dir }}/{{ site.sitename }}-bitrix/wwwroot"
  register: bitrix_to_init
  notify: init_bitrix
  changed_when: bitrix_to_init.matched == 0

- name: "{{ site.sitename }} - Create database and log directories for Percona"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}-bitrix/{{ item }}"
    state: directory
    mode: "0755"
    owner: polkitd
    group: mysql
  loop:
    - "db/mysql"
    - "log/mysql"

- name: "{{ site.sitename }} - Check/Create config directory structure"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/{{ item.path }}"
    state: directory
  loop: "{{ query('filetree', '../templates/bitrix/config') }}"
  when: item.state == 'directory'

- name: "{{ site.sitename }} - Generate common config for Bitrix"
  template:
    src: "{{ item.src }}"
    dest: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/{{ item.path }}"
  loop: "{{ query('filetree', '../templates/bitrix/config') }}"
  register: handle_restart_bitrix_config
  notify: restart_bitrix
  when: item.state == 'file'

- name: "{{ site.sitename }} - Generate /etc/hosts"
  template:
    src: "common/etc-hosts.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/hosts"
    force: yes
    backup: no

- name: "{{ site.sitename }} - Generate nginx configuration files for Bitrix"
  template:
    src: "bitrix/vhost-bitrix.conf.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/nginx/bx/site_enabled/vhost-bitrix.conf"
    force: yes
    backup: yes
  register: handle_restart_bitrix
  notify: restart_bitrix
  when: site.composite_mode | default (default_bitrix_composite_mode) == false

- name: "{{ site.sitename }} - Remove unnecessary configuration for Bitrix in Composite mode"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/nginx/bx/site_enabled/vhost-bitrix-composite.conf"
    state: absent
  when: site.composite_mode | default (default_bitrix_composite_mode) == false

- name: "{{ site.sitename }} - Generate nginx configuration files for Bitrix in Composite mode"
  template:
    src: "bitrix/vhost-bitrix-composite.conf.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/nginx/bx/site_enabled/vhost-bitrix-composite.conf"
    force: yes
    backup: yes
  register: handle_restart_bitrix_composite
  notify: restart_bitrix
  when: site.composite_mode | default (default_bitrix_composite_mode) == true

- name: "{{ site.sitename }} - Remove unnecessary configuration for Bitrix"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/nginx/bx/site_enabled/vhost-bitrix.conf"
    state: absent
  when: site.composite_mode | default (default_bitrix_composite_mode) == true

- name: "{{ site.sitename }} - Generate msmtp configuration files"
  template:
    src: "common/msmtprc.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}-bitrix/config/msmtprc"
    force: yes
    backup: no
    mode: "0600"
    owner: www-data
    group: www-data
  register: handle_restart_bitrix_msmtp
  notify: restart_bitrix