---
# Cloud storages configuration
- name: "{{ site.sitename }} - Create Cloud storages directory tree"
  file:
    path: "{{ cloudstorage_dir }}/{{ site.sitename }}-nextcloud/{{ item }}"
    state: directory
    mode: "0755"
    owner: www-data
    group: www-data
  loop:
    - "data"
    - "app"
    - "nginx"

- name: "{{ site.sitename }} - Create Cloud storages database directories"
  file:
    path: "{{ cloudstorage_dir }}/{{ site.sitename }}-nextcloud/db"
    state: directory
    mode: "0755"

- name: "{{ site.sitename }} - Generate nginx configuration file for Cloud storages"
  template:
    src: "cloudstorage/nginx.conf.j2"
    dest: "{{ cloudstorage_dir }}/{{ site.sitename }}-nextcloud/nginx/nginx.conf"
    force: yes
    backup: yes
  register: handle_restart_storage
  notify: restart_cloudstorage
