---
# tasks file for compose-gen.role

# Common tasks
- include: common.yml

# Traefik configuration
- include: traefik.yml

# Tick stack monitoring configuration
- include: monitoring.yml
  when: monitoring_enable

# Nextcloud (Main instance) configuration
- include: nextcloud.yml
  when: nextcloud_enable

# Plex configuration
- include: plex.yml
  when: plex_enable

# Transmission configuration
- include: transmission.yml
  when: transmission_enable

# NFS Server configuration
- include: nfs.yml
  when: nfs is defined

# Web sites configuration
- include: websites-dockerimages.yml
  loop: "{{ websites | flatten(levels=1) }}"
  loop_control:
    loop_var: site
  when:
    - websites is defined
    - site.application |default (default_application) == "generic"

- include: websites.yml
  loop: "{{ websites | flatten(levels=1) }}"
  loop_control:
    loop_var: site
  when:
    - websites is defined
    - site.application |default (default_application) == "generic"

# Bitrix-based web sites configuration
- include: bitrix.yml
  loop: "{{ websites | flatten(levels=1) }}"
  loop_control:
    loop_var: site
  when:
    - websites is defined
    - site.application |default (default_application) == "bitrix"

- include: bitrix-dockerimages.yml
  loop: "{{ websites | flatten(levels=1) }}"
  loop_control:
    loop_var: site
  when:
    - websites is defined
    - site.application |default (default_application) == "bitrix"

# Cloud storage instances configuration
- include: cloudstorages.yml
  loop: "{{ websites | flatten(levels=1) }}"
  loop_control:
    loop_var: site
  when:
    - websites is defined
    - site.application |default (default_application) == "nextcloud"

# Generate docker-compose file
- name: Generate docker-compose
  template:
    src: "docker-compose/docker-compose.yml.j2"
    dest: "{{ compose_dir }}/docker-compose.yml"
    force: yes
    backup: yes
  notify: compose_update
