- name: Create Docker images directory
  file:
    path: "{{compose_dir}}/images"
    state: directory
    mode: "0755"

- name: Create contexts for php-fpm backends
  file:
    path: "{{compose_dir}}/images/php-fpm-{{ item.backend_php_version | default (default_php_version) }}"
    state: directory
    mode: "0755"
  loop: "{{ websites | flatten(levels=1) }}"
  when: item.backend_type  | default ('fpm') == "fpm"

- name: Generate Dockerfiles for php-fpm backends
  template:
    src: "www/dockerfile-fpm.j2"
    dest: "{{compose_dir}}/images/php-fpm-{{ item.backend_php_version | default (default_php_version) }}/Dockerfile"
    force: yes
    backup: yes
  loop: "{{ websites | flatten(levels=1) }}"
  when: item.backend_type  | default ('fpm') == "fpm"
  notify: compose_build_images

- name: Create contexts for php/apache backends
  file:
    path: "{{compose_dir}}/images/php-{{ item.backend_php_version | default (default_php_version) }}-apache"
    state: directory
    mode: "0755"
  loop: "{{ websites | flatten(levels=1) }}"
  when: item.backend_type  | default ('fpm') == "apache"

- name: Generate Dockerfiles for php/apache backends
  template:
    src: "www/dockerfile-apache.j2"
    dest: "{{compose_dir}}/images/php-{{ item.backend_php_version | default (default_php_version) }}-apache/Dockerfile"
    force: yes
    backup: yes
  loop: "{{ websites | flatten(levels=1) }}"
  when: item.backend_type  | default ('fpm') == "apache"
  notify: compose_build_images
