---
# Web site configuration

- name: "{{ site.sitename }} - Create Web sites directory tree"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: www-data
    group: www-data
  loop:
    - "wwwroot"
    - "db"
    - "config"
    - "config/nginx"
    - "config/php"
    - "log"

- name: "{{ site.sitename }} - Create database and log directories for Percona/MySQL"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}/{{ item[1] }}"
    state: directory
    mode: "0755"
    owner: polkitd
    group: mysql
  loop:
    - "db/mysql"
    - "log/mysql"
  when: site.db_type | default (default_db_type) == "percona" or
        site.db_type | default (default_db_type) == "mysql"

- name: "{{ site.sitename }} - Create database directories for PostgreSQL"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}/db/postgresql"
    state: directory
    mode: "0755"
  when: site.db_type | default (default_db_type) == "postgresql"

- name: "{{ site.sitename }} - Check if Web site needs to be initialized"
  find:
    paths: "{{ sites_dir }}/{{ site.sitename }}/wwwroot"
  register: site_to_init
  notify: init_site
  changed_when: site_to_init.matched == 0

- name: "{{ site.sitename }} - Check/Create config directory structure"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}/config/{{ item.path }}"
    state: directory
  loop: "{{ query('filetree', '../templates/www/config') }}"
  when: item.state == 'directory'

- name: "{{ site.sitename }} - Generate common config files for Web Site"
  template:
    src: "{{ item.src }}"
    dest: "{{ sites_dir }}/{{ site.sitename }}/config/{{ item.path }}"
  loop: "{{ query('filetree', '../templates/www/config') }}"
  register: handle_restart_backend_config
  notify: restart_backend
  when: item.state == 'file'

- name: "{{ site.sitename }} - Generate /etc/hosts"
  template:
    src: "common/etc-hosts.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}/config/hosts"
    force: no
    backup: no

- name: "{{ site.sitename }} - Generate nginx configuration files for php-fpm"
  template:
    src: "www/vhost-fpm.conf.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}/config/nginx/vhost-fpm.conf"
    force: yes
    backup: yes
  when: site.backend_type | default (default_backend_type) == "fpm"
  register: handle_restart_frontend_fpm
  notify: restart_frontend

- name: "{{ site.sitename }} - Remove unnecessary configuration for apache"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}/config/nginx/vhost-apache.conf"
    state: absent
  when: site.backend_type | default (default_backend_type) == "fpm"

- name: "{{ site.sitename }} - Generate nginx configuration files for apache"
  template:
    src: "www/vhost-apache.conf.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}/config/nginx/vhost-apache.conf"
    force: yes
    backup: yes
  when: site.backend_type | default (default_backend_type) == "apache"
  register: handle_restart_frontend_apache
  notify: restart_frontend

- name: "{{ site.sitename }} - Remove unnecessary configuration for php-fpm"
  file:
    path: "{{ sites_dir }}/{{ site.sitename }}/config/nginx/vhost-fpm.conf"
    state: absent
  when: site.backend_type | default (default_backend_type) == "apache"

- name: "{{ site.sitename }} - Generate msmtp configuration files"
  template:
    src: "common/msmtprc.j2"
    dest: "{{ sites_dir }}/{{ site.sitename }}/config/msmtprc"
    force: yes
    backup: no
    mode: "0600"
    owner: www-data
    group: www-data
  register: handle_restart_backend_msmtp
  notify: restart_backend
