---
# handlers file for compose-gen.role

- name: Initialize Web site
  template:
    src: "www/phpinfo.php.j2"
    dest: "{{ item.invocation.module_args.paths[0] }}/index.php"
    force: no
    backup: no
  loop: "{{ site_to_init.results }}"
  listen: init_site

- name: Update docker-compose environment
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml up -d --remove-orphans"
  when: update_compose
  register: compose_updated
  listen: "update_compose"

- name: Restart Traefik
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart traefik"
  when:
    - update_compose
  listen: "restart_traefik"

- name: Restart Tick stack monitoring
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart mon-telegraf mon-influxdb mon-kapacitor mon-chronograf"
  when:
    - update_compose
    - compose_updated is undefined
  listen: "restart_monitoring"

- name: Restart Nextcloud (Main Instance)
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart nextcloud-db nextcloud-redis nextcloud-app nextcloud-cron nextcloud-frontend"
  when:
    - update_compose
    - compose_updated is undefined
  listen: "restart_nextcloud"

- name: Restart Plex
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart plex-app plex-proxy"
  when:
    - update_compose
    - compose_updated is undefined
  listen: "restart_plex"

- name: Stop Transmission
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml stop loader"
  when: update_compose
  listen: "restart_transmission"

- name: Update Transmission config
  copy:
    src: "{{ base_dir }}/transmission/settings.json.bak"
    dest: "{{ base_dir }}/transmission/settings.json"
    remote_src: yes
  when: update_compose
  listen: "restart_transmission"

- name: Start Transmission
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml start loader"
  when: update_compose
  listen: "restart_transmission"

- name: Restart NFS Server
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart nfs-server"
  when:
    - update_compose
    - compose_updated is undefined
  listen: "restart_nfs"

- name: Restart Website (php-fpm)
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart {{ item.item.sitename }}-nginx"
  loop: "{{ handle_restart_website_fpm.results | selectattr('changed', 'equalto', true) | list }}"
  when: update_compose
  listen: "restart_website"

- name: Restart Website (Apache)
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart {{ item.item.sitename }}-nginx"
  loop: "{{ handle_restart_website_apache.results | selectattr('changed', 'equalto', true) | list }}"
  when: update_compose
  listen: "restart_website"

- name: Restart Cloud storage
  command: "docker-compose -f {{ compose_dir }}/docker-compose.yml restart {{ item.item.sitename }}-nextcloud-db {{ item.item.sitename }}-nextcloud-redis {{ item.item.sitename }}-nextcloud-app {{ item.item.sitename }}-nextcloud-cron {{ item.item.sitename }}-nextcloud-frontend"
  loop: "{{ handle_restart_storage.results | selectattr('changed', 'equalto', true) | list }}"
  when:
    - update_compose
    - compose_updated is undefined
  listen: "restart_cloudstorage"
